# SPDX-FileCopyrightText: Copyright (c) 2016-2025 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: pit
'on':
  push:
    branches:
      - master
jobs:
  pit:
    timeout-minutes: 90
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ubuntu-jdk-21-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ubuntu-jdk-21-maven-
      - run: mvn clean install "-Ppit,deep"
  report:
    name: Create issue on failure
    needs: pit
    if: failure() && github.event.pull_request == null
    runs-on: ubuntu-24.04
    steps:
      - uses: jayqi/failed-build-issue-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
